# TF Syntax Basics

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.13.1


In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [9]:
print(result)

b'Hello World'


In [10]:
a = tf.constant(10)

In [12]:
b = tf.constant(20)

In [13]:
type(a)

tensorflow.python.framework.ops.Tensor

In [14]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [15]:
a + b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [16]:
a + b

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [17]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [18]:
print(result)

30


In [19]:
const = tf.constant(10)

In [22]:
fill_mat = tf.fill((4, 4), 10)

In [23]:
myzeros = tf.zeros((4, 4))

In [24]:
myones = tf.ones((4, 4))

In [25]:
myrandn = tf.random_normal((4, 4), mean=0, stddev=1.0)

In [26]:
myrandu = tf.random_uniform((4, 4), minval=0, maxval=1)

In [27]:
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [28]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [29]:
sess = tf.InteractiveSession()

In [30]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.45621148  1.8319542  -0.30301353  1.123569  ]
 [-0.10581903 -0.88189256  1.3670657  -0.0324664 ]
 [ 1.3581595   0.12621537 -0.40579557  1.058053  ]
 [-1.1534932  -1.1784647   0.8737559   0.79254144]]


[[0.0783937  0.3726585  0.63514066 0.13431299]
 [0.678648   0.5165235  0.23781371 0.8266871 ]
 [0.314098   0.8424722  0.83618915 0.7069714 ]
 [0.7178452  0.48843777 0.2347039  0.75407577]]




In [31]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.6896564  -0.36782977  0.14014345  0.803596  ]
 [-0.0614397   0.1803609  -0.40534276 -1.6917893 ]
 [-0.19803824 -0.45857614 -1.6177443   0.8494536 ]
 [ 0.18705364  0.18587655  0.14126413  1.4148405 ]]


[[0.57134354 0.1941024  0.10502708 0.6540147 ]
 [0.1165849  0.5330527  0.7848635  0.2243123 ]
 [0.6556448  0.5864377  0.76518583 0.8253654 ]
 [0.5877613  0.42475355 0.70240533 0.64676714]]




In [32]:
a = tf.constant([[1,2],
                [3,4]])

In [33]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [34]:
b = tf.constant([[10], 
                 [100]])

In [35]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [36]:
result = tf.matmul(a, b)

In [37]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [38]:
result.eval()

array([[210],
       [430]], dtype=int32)